# Generated by Django 3.2.16 on 2022-11-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('owner', models.CharField(max_length=50, verbose_name='负责人')),
                ('tel', models.CharField(max_length=20, verbose_name='联系电话')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
        ),
    ]
