# Generated by Django 3.2.16 on 2022-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20221207_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '合同'), ('2', '订单')], max_length=1, null=True),
        ),
    ]
