# Generated by Django 3.2.16 on 2022-12-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='type',
            new_name='types',
        ),
        migrations.AlterField(
            model_name='contract',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
