# Generated by Django 3.2.16 on 2022-12-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20221207_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='contracts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
    ]
