# Generated by Django 3.2.16 on 2022-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_attachment_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
