# Generated by Django 3.2.16 on 2022-12-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_attachment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='name',
        ),
    ]
