# Generated by Django 3.2.16 on 2022-12-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='doc_file',
            field=models.FileField(default='', upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
    ]
