# Generated by Django 3.2.16 on 2022-12-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_auto_20221208_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
    ]
