# Generated by Django 3.2.16 on 2022-12-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_remove_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='owner',
            field=models.CharField(default='', max_length=50, verbose_name='负责人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='types',
            field=models.CharField(choices=[('1', '合同'), ('2', '订单')], default='1', max_length=1),
        ),
    ]
