# Generated by Django 3.2.16 on 2022-12-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_auto_20221208_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='文件名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='状态'),
        ),
    ]
