# Generated by Django 3.2.16 on 2022-12-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_auto_20221209_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='文件名称'),
        ),
    ]
