# Generated by Django 3.2.16 on 2022-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_auto_20221209_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文件名称'),
        ),
    ]
