# Generated by Django 3.2.16 on 2022-12-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_attachment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='update_datetime',
        ),
    ]
